import posts from '../../public/data/posts.json';
import Head from 'next/head'

export default function BlogPost({ post }) {
    return (
        <>
            <Head>
                <title>{`${post.title} - Milanesi Propiedades`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <h3>{post.title}</h3>
            </div>
        </>
    )
  }

export async function getStaticProps(context) {
    return {
        props: {
            post: posts.find(post => post.slug === context.params.slug)
        }
     }
}
  
export async function getStaticPaths() {
    return {
        paths: posts.map(post => ({ params: { slug: post.slug } })),
        fallback: false
    }
}